Add workaround to prevent simultaneous builds from starting on the wrong node (#30)
jenkinsci/scoring-load-balancer-plugin pull request #54
Opened 2024-06-22 09:33 UTC by voruti

see Discussion at https://github.com/jenkinsci/scoring-load-balancer-plugin/issues/30#issuecomment-2182665516

### Testing done

With this workaround, all builds are scheduled on the correct node, but there also is an additional/artificial delay added to the builds.

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] ~Link to relevant pull requests, esp. upstream and downstream changes~
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2024-06-23 09:05 UTC, viceice reviewed
looks good so far. I think a second delay is acceptable. we should make it configurable.

this also needs some tests, I don't know how to fake time inside Java tests.

I'll ask on Jenkins mailing list later if there's a better way

2024-07-08 08:18 UTC, viceice commented
Can you please fix the conflict?

2024-07-13 12:08 UTC, voruti commented
- [x] make it configurable
- [ ] Japanese translation/strings (I can't do this myself)
- [ ] Tests

2024-09-26 07:22 UTC, voruti commented
@viceice Any suggestion on how we can proceed with this? Should we skip the missing translation?

2024-12-02 10:39 UTC, timja commented
I don't understand it enough, better to ask on the mailing list with a concise description of the problem, linking here

2025-01-23 10:16 UTC, viceice requested changes

2025-01-23 10:16 UTC, viceice commented on src/main/resources/jp/ikedam/jenkins/plugins/scoringloadbalancer/ScoringLoadBalancer/help-simultaneousBuildsWorkaroundEnabled_ja.html
> +TODO
i don't know the best practices, but shouldn't we at lease use the english text here or remove the file to have the default help message?

2025-01-23 10:16 UTC, viceice commented on src/main/resources/jp/ikedam/jenkins/plugins/scoringloadbalancer/ScoringLoadBalancer/help-simultaneousBuildsWorkaroundThrottleTime_ja.html
> +TODO
same here

2025-01-23 10:17 UTC, viceice commented
it seems it needs somwe test fixes too

2025-01-23 20:10 UTC, voruti commented
> it seems it needs somwe test fixes too

The failing test `testTwoSimultaneousBuilds_runsOnWrongNodeWithoutWorkaround` indicates that the workaround is no longer necessary. I'll dive into the Jenkins source code to find out what's going on...

2025-01-23 22:01 UTC, voruti commented
> I'll dive into the Jenkins source code to find out what's going on...

Strange and unstable things are going on. The following log is *without* the workaround:
```shell
2025-01-23 21:35:00.547+0000 [id=142]   INFO    j.i.j.p.s.ScoringLoadBalancer#reportScores: Scoring for hudson.model.FreeStyleProject@17dddd48[TestJob1]:
                 Node3: 1000
                      : -500
2025-01-23 21:35:00.550+0000 [id=142]   INFO    j.i.j.p.s.ScoringLoadBalancer#reportScores: Scoring for hudson.model.FreeStyleProject@44b16915[TestJob2]:
                      : -500
2025-01-23 21:35:30.757+0000 [id=147]   INFO    j.i.j.p.s.ScoringLoadBalancer#reportScores: Scoring for hudson.model.FreeStyleProject@44b16915[TestJob2]:
                 Node3: 1000
                      : -500
2025-01-23 21:35:32.538+0000 [id=149]   INFO    j.i.j.p.s.ScoringLoadBalancer#reportScores: Scoring for hudson.model.FreeStyleProject@17dddd48[TestJob1]:
                 Node3: 1000
                      : -500
2025-01-23 21:36:02.463+0000 [id=152]   INFO    j.i.j.p.s.ScoringLoadBalancer#reportScores: Scoring for hudson.model.FreeStyleProject@44b16915[TestJob2]:
                 Node3: 1000
                      : -500
2025-01-23 21:36:04.246+0000 [id=154]   INFO    j.i.j.p.s.ScoringLoadBalancer#reportScores: Scoring for hudson.model.FreeStyleProject@17dddd48[TestJob1]:
                 Node3: 1000
                      : -500
2025-01-23 21:37:00.534+0000 [id=159]   INFO    j.i.j.p.s.ScoringLoadBalancer#reportScores: Scoring for hudson.model.FreeStyleProject@17dddd48[TestJob1]:
                 Node3: 1000
                      : -500
2025-01-23 21:37:00.535+0000 [id=159]   INFO    j.i.j.p.s.ScoringLoadBalancer#reportScores: Scoring for hudson.model.FreeStyleProject@44b16915[TestJob2]:
                      : -500
2025-01-23 21:38:00.534+0000 [id=166]   INFO    j.i.j.p.s.ScoringLoadBalancer#reportScores: Scoring for hudson.model.FreeStyleProject@17dddd48[TestJob1]:
                 Node3: 1000
                      : -500
2025-01-23 21:38:00.534+0000 [id=166]   INFO    j.i.j.p.s.ScoringLoadBalancer#reportScores: Scoring for hudson.model.FreeStyleProject@44b16915[TestJob2]:
                      : -500
2025-01-23 21:39:00.534+0000 [id=174]   INFO    j.i.j.p.s.ScoringLoadBalancer#reportScores: Scoring for hudson.model.FreeStyleProject@17dddd48[TestJob1]:
                 Node3: 1000
                      : -500
2025-01-23 21:39:00.534+0000 [id=174]   INFO    j.i.j.p.s.ScoringLoadBalancer#reportScores: Scoring for hudson.model.FreeStyleProject@44b16915[TestJob2]:
                      : -500
```
Sometimes the (new) default behaviour of Jenkins chooses the correct nodes/executors, sometimes it doesn't, just as before.

So the workaround is still required to get to choosing correct nodes all the time.
Testing that the workaround is required is just not that easy, as the results are unstable.

2025-01-23 22:02 UTC, voruti commented on src/main/resources/jp/ikedam/jenkins/plugins/scoringloadbalancer/ScoringLoadBalancer/help-simultaneousBuildsWorkaroundEnabled_ja.html
> +TODO
I don't know either. Who can help?

2025-01-27 22:07 UTC, viceice commented
do you find the users who changed the Jenkins code recently? so we could ask them for help?

2025-01-28 07:42 UTC, voruti commented
> do you find the users who changed the Jenkins code recently? so we could ask them for help?

No, unfortunately I didn't find a code location that would explain this behavior.

2025-03-26 09:28 UTC, viceice commented
this is now conflicted, please deconflict. I'll merge the workaround then.

2025-03-26 20:20 UTC, voruti commented
> this is now conflicted, please deconflict.

I need to add the configuration as code stuff for that. Maybe I have time on the weekend.

2025-03-29 15:43 UTC, voruti commented on src/main/resources/jp/ikedam/jenkins/plugins/scoringloadbalancer/ScoringLoadBalancer/help-simultaneousBuildsWorkaroundEnabled_ja.html
> +TODO
What about this? Should I just remove these files?

2025-04-01 13:12 UTC, viceice commented on src/main/java/jp/ikedam/jenkins/plugins/scoringloadbalancer/ScoringLoadBalancer.java
> +            this.simultaneousBuildsWorkaroundThrottleTime = 1000;
Can we cover this by tests?

2025-04-01 13:15 UTC, viceice commented on src/test/java/jp/ikedam/jenkins/plugins/scoringloadbalancer/SimultaneousBuildsWorkaroundTest.java
> +    @Rule
Use junit5 style for new test files. we'll migrate the exiting tests soon., see
- #113

2025-04-01 18:13 UTC, voruti commented on src/main/resources/jp/ikedam/jenkins/plugins/scoringloadbalancer/ScoringLoadBalancer/help-simultaneousBuildsWorkaroundEnabled_ja.html
> +TODO
I removed them.

While testing, I noticed that even the other translation files (which already are translated into Japanese) like `help-enabled_ja.html` don't show seem to work:
![grafik](https://github.com/user-attachments/assets/1804d22e-a293-4292-ad73-7ac6e0cadc41)

2025-04-01 18:52 UTC, voruti commented on src/test/resources/configuration-as-code-test.yml
> +    simultaneousBuildsWorkaroundThrottleTime: 2000
As far as I understand _this specific test_ only tests loading/reading the specified configuration file. I think there are no jobs/builds started _on this test_.

2025-04-01 18:53 UTC, voruti commented on src/test/resources/configuration-as-code-test.yml
> +    simultaneousBuildsWorkaroundThrottleTime: 2000
see https://github.com/jenkinsci/scoring-load-balancer-plugin/blob/0d41f89bbaf775c2b802a7598dece1fb3831b090/src/test/java/jp/ikedam/jenkins/plugins/scoringloadbalancer/ConfigurationAsCodeTest.java#L23

2025-04-01 19:40 UTC, voruti commented on src/main/java/jp/ikedam/jenkins/plugins/scoringloadbalancer/ScoringLoadBalancer.java
> +            this.simultaneousBuildsWorkaroundThrottleTime = 1000;
It wasn't before and it's a deprecated method, however I now created a test for it: [`5074ba0` (#54)](https://github.com/jenkinsci/scoring-load-balancer-plugin/pull/54/commits/5074ba0c785a9cb1aa7e5958849640aa2f255a9d)

2025-04-02 06:27 UTC, viceice commented on src/main/resources/jp/ikedam/jenkins/plugins/scoringloadbalancer/ScoringLoadBalancer/help-simultaneousBuildsWorkaroundEnabled_ja.html
> +TODO
🤷‍♂️ I don't know enough about Jenkins translation to help. so simply don't add these empty Todo files.

2025-04-02 06:35 UTC, viceice approved these changes

2025-04-02 06:35 UTC, viceice commented on src/test/java/jp/ikedam/jenkins/plugins/scoringloadbalancer/SimultaneousBuildsWorkaroundTest.java
> + * Copyright (c) 2013 IKEDA Yasuyuki
you can set yourself if you want

2025-04-02 12:20 UTC, viceice commented
please fix merge conflicts 😇

2025-04-03 20:05 UTC, viceice approved these changes

2025-04-03 20:06 UTC, merged